function namesmaps = importfile(workbookFile, sheetName, dataLines)

%Matlab's self generated function to import animal ID names as well as
%segmentation mask names from an excel sheet


%IMPORTFILE3 Import data from a spreadsheet
%  NAMESMAPS = IMPORTFILE3(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a string array.
%
%  NAMESMAPS = IMPORTFILE3(FILE, SHEET) reads from the specified
%  worksheet.
%
%  NAMESMAPS = IMPORTFILE3(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  namesmaps = importfile3("C:\Users\alita\AppData\Roaming\MathWorks\MATLAB Add-Ons\Collections\T2_mapping\names_maps.xlsx", "Sheet1", [2, 146]);
%
%  See also READMATRIX.
%
% Auto-generated by MATLAB on 14-Jul-2021 22:45:41

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 131];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 1);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":A" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = "R19445_D28_T2Mapnii";
opts.VariableTypes = "string";

% Specify variable properties
opts = setvaropts(opts, "R19445_D28_T2Mapnii", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "R19445_D28_T2Mapnii", "EmptyFieldRule", "auto");

% Import the data
namesmaps = readmatrix(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":A" + dataLines(idx, 2);
    tb = readmatrix(workbookFile, opts, "UseExcel", false);
    namesmaps = [namesmaps; tb]; %#ok<AGROW>
end

end